# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnterTodayDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_enter_today_dialog(object):
    def setupUi(self, enter_today_dialog):
        enter_today_dialog.setObjectName("enter_today_dialog")
        enter_today_dialog.resize(923, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(enter_today_dialog.sizePolicy().hasHeightForWidth())
        enter_today_dialog.setSizePolicy(sizePolicy)
        enter_today_dialog.setMinimumSize(QtCore.QSize(0, 700))
        self.tableView = QtWidgets.QTableView(enter_today_dialog)
        self.tableView.setGeometry(QtCore.QRect(20, 80, 871, 501))
        self.tableView.setMinimumSize(QtCore.QSize(0, 100))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(enter_today_dialog)
        self.label.setGeometry(QtCore.QRect(10, -60, 900, 207))
        font = QtGui.QFont()
        font.setFamily("Hei")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 18pt \"Hei\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(enter_today_dialog)
        QtCore.QMetaObject.connectSlotsByName(enter_today_dialog)

    def retranslateUi(self, enter_today_dialog):
        _translate = QtCore.QCoreApplication.translate
        enter_today_dialog.setWindowTitle(_translate("enter_today_dialog", "当日入库"))
        self.label.setText(_translate("enter_today_dialog", "当日入库 "))
