# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnterTodayDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_enter_today_dialog(object):
    def setupUi(self, enter_today_dialog):
        enter_today_dialog.setObjectName("enter_today_dialog")
        enter_today_dialog.resize(923, 283)
        self.splitter = QtWidgets.QSplitter(enter_today_dialog)
        self.splitter.setGeometry(QtCore.QRect(10, 20, 900, 207))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(self.splitter)
        self.tableView.setObjectName("tableView")

        self.retranslateUi(enter_today_dialog)
        QtCore.QMetaObject.connectSlotsByName(enter_today_dialog)

    def retranslateUi(self, enter_today_dialog):
        _translate = QtCore.QCoreApplication.translate
        enter_today_dialog.setWindowTitle(_translate("enter_today_dialog", "查询结果"))
        self.label.setText(_translate("enter_today_dialog", "当日入库 "))
