# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManDiag.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(700, 600))
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 511, 328))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_ID = QtWidgets.QLabel(self.layoutWidget)
        self.label_ID.setStyleSheet("font: 13pt \"Hei\";")
        self.label_ID.setObjectName("label_ID")
        self.gridLayout.addWidget(self.label_ID, 0, 1, 1, 1)
        self.label_type = QtWidgets.QLabel(self.layoutWidget)
        self.label_type.setStyleSheet("font: 13pt \"Hei\";")
        self.label_type.setObjectName("label_type")
        self.gridLayout.addWidget(self.label_type, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("font: 13pt \"Hei\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 1)
        self.lineEdit_pID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pID.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_pID.setText("")
        self.lineEdit_pID.setObjectName("lineEdit_pID")
        self.gridLayout.addWidget(self.lineEdit_pID, 1, 1, 1, 1)
        self.lineEdit_result = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_result.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_result.setText("")
        self.lineEdit_result.setPlaceholderText("")
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.gridLayout.addWidget(self.lineEdit_result, 3, 1, 1, 1)
        self.lineEdit_describe = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_describe.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_describe.setText("")
        self.lineEdit_describe.setPlaceholderText("")
        self.lineEdit_describe.setObjectName("lineEdit_describe")
        self.gridLayout.addWidget(self.lineEdit_describe, 6, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 420, 210, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_commit = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_commit.sizePolicy().hasHeightForWidth())
        self.btn_commit.setSizePolicy(sizePolicy)
        self.btn_commit.setStyleSheet("font: 13pt \"Hei\";")
        self.btn_commit.setAutoDefault(False)
        self.btn_commit.setObjectName("btn_commit")
        self.horizontalLayout.addWidget(self.btn_commit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "人工诊断"))
        self.label_ID.setText(_translate("Dialog", "病人编号"))
        self.label_type.setText(_translate("Dialog", "检验结果"))
        self.label.setText(_translate("Dialog", "描述"))
        self.lineEdit_pID.setPlaceholderText(_translate("Dialog", "p******"))
        self.btn_commit.setText(_translate("Dialog", "提交"))
import creat_rc
