# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pvalueWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_p_diag(object):
    def setupUi(self, p_diag):
        p_diag.setObjectName("p_diag")
        p_diag.resize(800, 600)
        self.frame = QtWidgets.QFrame(p_diag)
        self.frame.setGeometry(QtCore.QRect(120, 120, 521, 251))
        self.frame.setStyleSheet("\n"
"border-image: url(:/newPrefix/pictures/p.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.retranslateUi(p_diag)
        QtCore.QMetaObject.connectSlotsByName(p_diag)

    def retranslateUi(self, p_diag):
        _translate = QtCore.QCoreApplication.translate
        p_diag.setWindowTitle(_translate("p_diag", "方法选择"))
import icon_rc
