# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatientSearch.ui'

# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(720, 466)
        self.btn_search = QtWidgets.QPushButton(Dialog)
        self.btn_search.setGeometry(QtCore.QRect(10, 390, 93, 28))
        self.btn_search.setObjectName("btn_search")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 101, 256))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_name.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout.addWidget(self.lineEdit_name)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_pID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pID.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_pID.setText("")
        self.lineEdit_pID.setObjectName("lineEdit_pID")
        self.verticalLayout.addWidget(self.lineEdit_pID)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_sID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_sID.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_sID.setText("")
        self.lineEdit_sID.setObjectName("lineEdit_sID")
        self.verticalLayout.addWidget(self.lineEdit_sID)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_eID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_eID.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_eID.setText("")
        self.lineEdit_eID.setObjectName("lineEdit_eID")
        self.verticalLayout.addWidget(self.lineEdit_eID)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "查询窗口"))
        self.btn_search.setText(_translate("Dialog", "查询"))
        self.label.setText(_translate("Dialog", "病人姓名"))
        self.lineEdit_name.setPlaceholderText(_translate("Dialog", "姓名"))
        self.label_2.setText(_translate("Dialog", "病人编号"))
        self.lineEdit_pID.setPlaceholderText(_translate("Dialog", "编号"))
        self.label_3.setText(_translate("Dialog", "样本编号"))
        self.lineEdit_sID.setPlaceholderText(_translate("Dialog", "编号"))
        self.label_4.setText(_translate("Dialog", "结果编号"))
        self.lineEdit_eID.setPlaceholderText(_translate("Dialog", "编号"))
