# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecycleBinDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecycleBinDialog(object):
    def setupUi(self, RecycleBinDialog):
        RecycleBinDialog.setObjectName("RecycleBinDialog")
        RecycleBinDialog.resize(922, 283)
        self.splitter = QtWidgets.QSplitter(RecycleBinDialog)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 900, 207))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(self.splitter)
        self.tableView.setObjectName("tableView")

        self.retranslateUi(RecycleBinDialog)
        QtCore.QMetaObject.connectSlotsByName(RecycleBinDialog)

    def retranslateUi(self, RecycleBinDialog):
        _translate = QtCore.QCoreApplication.translate
        RecycleBinDialog.setWindowTitle(_translate("RecycleBinDialog", "回收站"))
        self.label.setText(_translate("RecycleBinDialog", "回收站"))
