# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SampleClassDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sample_class_dialog(object):
    def setupUi(self, sample_class_dialog):
        sample_class_dialog.setObjectName("sample_class_dialog")
        sample_class_dialog.resize(923, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sample_class_dialog.sizePolicy().hasHeightForWidth())
        sample_class_dialog.setSizePolicy(sizePolicy)
        sample_class_dialog.setMinimumSize(QtCore.QSize(200, 800))
        self.label = QtWidgets.QLabel(sample_class_dialog)
        self.label.setGeometry(QtCore.QRect(410, 40, 60, 16))
        self.label.setObjectName("label")

        self.retranslateUi(sample_class_dialog)
        QtCore.QMetaObject.connectSlotsByName(sample_class_dialog)

    def retranslateUi(self, sample_class_dialog):
        _translate = QtCore.QCoreApplication.translate
        sample_class_dialog.setWindowTitle(_translate("sample_class_dialog", "样本类别"))
        self.label.setText(_translate("sample_class_dialog", "TextLabel"))
