# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_data_dialog(object):
    def setupUi(self, show_data_dialog):
        show_data_dialog.setObjectName("show_data_dialog")
        show_data_dialog.resize(923, 283)
        self.splitter = QtWidgets.QSplitter(show_data_dialog)
        self.splitter.setGeometry(QtCore.QRect(10, 30, 900, 207))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(self.splitter)
        self.tableView.setObjectName("tableView")

        self.retranslateUi(show_data_dialog)
        QtCore.QMetaObject.connectSlotsByName(show_data_dialog)

    def retranslateUi(self, show_data_dialog):
        _translate = QtCore.QCoreApplication.translate
        show_data_dialog.setWindowTitle(_translate("show_data_dialog", "查询结果"))
        self.label.setText(_translate("show_data_dialog", "查询结果"))
