# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(600, 500))
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 70, 327, 122))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_group = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_group.setObjectName("comboBox_group")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.gridLayout.addWidget(self.comboBox_group, 1, 0, 1, 1)
        self.comboBox_data = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_data.setObjectName("comboBox_data")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.gridLayout.addWidget(self.comboBox_data, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setStyleSheet("font: 75 13pt \"Heiti SC\";")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.comboBox_method = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.gridLayout.addWidget(self.comboBox_method, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_result = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_result.setObjectName("label_result")
        self.gridLayout.addWidget(self.label_result, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "显著性分析"))
        self.label.setText(_translate("Dialog", "组别"))
        self.comboBox_group.setItemText(0, _translate("Dialog", "VWD类型"))
        self.comboBox_group.setItemText(1, _translate("Dialog", "血友病类型"))
        self.comboBox_group.setItemText(2, _translate("Dialog", "出血/血栓"))
        self.comboBox_group.setItemText(3, _translate("Dialog", "血型"))
        self.comboBox_group.setItemText(4, _translate("Dialog", "性别"))
        self.comboBox_data.setItemText(0, _translate("Dialog", "年龄"))
        self.comboBox_data.setItemText(1, _translate("Dialog", "APTT"))
        self.comboBox_data.setItemText(2, _translate("Dialog", "Ag"))
        self.comboBox_data.setItemText(3, _translate("Dialog", "Act"))
        self.comboBox_data.setItemText(4, _translate("Dialog", "RIPA"))
        self.pushButton.setText(_translate("Dialog", "确定"))
        self.label_3.setText(_translate("Dialog", "方法"))
        self.label_2.setText(_translate("Dialog", "指标"))
        self.comboBox_method.setItemText(0, _translate("Dialog", "T-test"))
        self.comboBox_method.setItemText(1, _translate("Dialog", "ANOVA"))
        self.comboBox_method.setItemText(2, _translate("Dialog", "Mann-Whitney"))
        self.comboBox_method.setItemText(3, _translate("Dialog", "Kruskal-Wallis"))
        self.label_4.setText(_translate("Dialog", "p-value"))
        self.label_result.setText(_translate("Dialog", " "))
import creat_rc
